### ISSUE TITLE
How to handle DEBUG

### ISSUE THREAD

**Issue by MarcosX** [mavcunha/devcli#3]
The way to debug currently is by running the command with `_DEBUG` but for some reason it was always being set to `true` regardless of how we passed the command or even defined the variable. 

We also noticed that it only happens in the `else` of an `if` that checks the bash version, which seems odd.

On our CLI we just removed the `DEBUG` set line (`devcli:31`) and used a plain env var to enable/disable debug logs, like `DEBUG=true leave-cli test unit`.

If removing that line will cause trouble elsewhere, another option would be to check if the env var is already set and only execute the logic if it isn't, like this:

```bash
DEBUG=${DEBUG:-$(eval "[[ -n \${${MAIN_COMMAND^^}_DEBUG} ]] && echo 'true' ")}
```

Let us know what you think and we can make a PR with these changes.

**Comment by mavcunha** [comment]
There's two things, the first is that the debug flag is set to `COMMAND_DEBUG` and not only `_DEBUG`, for example if the command is called `mycmd` the debug mode should be set by `MYCMD_DEBUG=true` (or anything that makes the environment variable set).  Internally the CLI should set the DEBUG variable to true. At least this is the expected behavior. 

The second thing is the `else` clause where the flag is set. This was done because the `^^` (turn the string to upper case) is only available in bash >= 4. This was a shortcut at the time, but also the CLI assumes bash >= 4 in several instances. The check was necessary for macOS computer which I guess still ship with bash 3 by default despite being 8 years of bash 4 release. :/ 

Does this explain and helps on the behavior you're seeing or is still a bug?

**Comment by MarcosX** [comment]
I does help, thanks! We didn't figure out that the actual variable should be `COMMAND_DEBUG`. But by default (if no env var is set) it seems that `DEBUG` will be set to true, maybe consider switching it to be disabled by default and then we can add in the docs how to debug commands?

**Comment by mavcunha** [comment]
Wasn't supposed to be true by default, here's an example:

Create a subcommand just to test the debug message (called the subcommand test in this case)
```
log "Debug is enabled"
echo "Debug var is: ${DEBUG}"
```

First run without any debug variable:
```
(master)$ devcli test
Debug var is:

Showing 'devcli test' available actions

```
Now enabling the debug mode:
```
(master)$ DEVCLI_DEBUG=true devcli test
debug: check if devcli is on PATH
debug: got argument 'test'
debug: arguments 'test'
debug: checking if '/Users/mvaltas/Projects/devcli/devcli.d/test' exists
debug: running /Users/mvaltas/Projects/devcli/devcli.d/test
debug: Debug is enabled
Debug var is: true
debug: showing 'test' help

Showing 'devcli test' available actions

```

Sometimes we end up with environment variables on the main shell, can you double check? It appears that it is working as supposed to.

**Comment by MarcosX** [comment]
Yep, it's working as expected. Not sure what happened before though! Thanks!
